### Failed REGISTER no passwords at all

POST http://localhost:3090/users/register HTTP/1.1
content-type: application/json

    {
        "email": "test@test.com"
    }


### Failed REGISTER not same password

POST http://localhost:3090/users/register HTTP/1.1
content-type: application/json

    {
        "email": "test@test.com",
        "password": "12345678",
        "repeatpassword": "notTheSamePassword"
    }


### Successful REGISTER

POST http://localhost:3090/users/register HTTP/1.1
content-type: application/json

    {
        "email": "test@test.com",
        "password": "12345678",
        "repeatpassword": "12345678"
    }

### Failed LOGIN
# @name postLoginFailure
POST http://localhost:3090/users/login HTTP/1.1
content-type: application/json

    {
        "email": "test3@test.com",
        "password": "notThePassword"
    }

### Successful LOGIN
# @name postLoginSuccess
POST http://localhost:3090/users/login HTTP/1.1
content-type: application/json

{
    "email": "test3@test.com",
    "password": "12345678"
}


### Failed PROTECTED
@token = {{postLoginFailure.response.body.token}}
GET http://localhost:3090/users/protected HTTP/1.1
content-type: application/json
Authorization: notAJwt

### Successful PROTECTED
@token = {{postLoginSuccess.response.body.token}}
GET http://localhost:3090/users/protected HTTP/1.1
content-type: application/json
Authorization: {{token}}
